version: '3.7'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prayer_check_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
    networks:
      - prayercheck-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prayer_check_db
    ports:
      - "3306:3306"
    networks:
      - prayercheck-network

networks:
  prayercheck-network:
    driver: bridge
